name: awrad_app
description: Majmua Awrad wa Wazaif + PanjSurah Shareef - Islamic Book App
publish_to: 'none'
version: 1.3.4+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2
  http: ^1.3.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  share_plus: ^10.0.2
  in_app_review: ^2.0.9
  connectivity_plus: ^6.1.1
  google_mobile_ads: ^5.3.1
  scrollable_positioned_list: ^0.3.8
  audio_service: ^0.18.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.1
  # Tool for app icon generation
  flutter_launcher_icons: ^0.13.1
  # Tool for image conversion
  image: ^4.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/logo.png"
  adaptive_icon_background: "#1B5E20"
  adaptive_icon_foreground: "assets/imgs/logo.png"

flutter:
  uses-material-design: true
  
  fonts:
    - family: JameelNooriNastaliq
      fonts:
        - asset: "assets/fonts/Jameel Noori Nastaleeq.ttf"

  assets:
    - assets/imgs/
    - assets/pages/
    - assets/panjsurah/yaseen/
    - assets/panjsurah/kehf/
    - assets/panjsurah/rehman/
    - assets/panjsurah/waqia/
    - assets/panjsurah/mulk/
    - assets/panjsurah/fatah/
    - assets/panjsurah/muzzamil/
    - assets/panjsurah/deen/
    - assets/panjsurah/baqrah/
    - assets/panjsurah/fatiha/
    - assets/panjsurah/falaq/
    - assets/panjsurah/kursi/
    - assets/panjsurah/hashar/
    - assets/panjsurah/kalma/
    - assets/panjsurah/kalmaastaghfar/
    - assets/panjsurah/darood/
    - assets/panjsurah/dua/
    - assets/panjsurah/nama/
    - assets/panjsurah/nimzazkar/
    - assets/panjsurah/zikar/
    - assets/panjsurah/kafal/
    - assets/panjsurah/hajat/
    - assets/panjsurah/khajgan/
    - assets/panjsurah/kull2/
    - assets/panjsurah/bakhsish/
    - assets/panjsurah/izkar/
    - assets/panjsurah/sawab/
    - assets/panjsurah/shifamahi/
    - assets/panjsurah/tajtunjina/
    - assets/panjsurah/mufassil/
